sudo: required
dist: xenial

addons:
  postgresql: "9.5"

services:
  - docker
  - mysql

before_script:
  - psql -c 'create database sqlalchemy_utils_test;' -U postgres
  - psql -c 'create extension hstore;' -U postgres -d sqlalchemy_utils_test
  - mysql -e 'create database sqlalchemy_utils_test;'

language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
env:
  global:
    - TOXENV='py-sqla{1.3,1.4}'

matrix:
  include:
  - python: 3.7
    env: TOXENV='lint'

install:
  - source $TRAVIS_BUILD_DIR/.travis/install_mssql.sh
  - pip install tox

script:
  - tox
